# NumPy로 수치 계산

## 기본 벡터 계산

### 다차원 배열

### ndarray

### NumPy는 왜 벡터 계산이 빠를까?

In [5]:
from random import random

list_1 = [random() for _ in range(1000000)]
list_2 = [random() for _ in range(1000000)]

In [3]:
out = [x + y for (x, y) in zip(list_1, list_2)]
out

[0.9928743314073356,
 1.0845017953433376,
 0.5663401804549703,
 1.0504815584916258,
 0.804947705446862,
 0.6835398002228718,
 1.5998502907615904,
 0.5479613443806414,
 0.1739720274162032,
 1.4279429985144059,
 0.9325398656772433,
 1.102585949091315,
 1.3927159166170118,
 1.2098630845189828,
 0.5057289467126271,
 0.6658160774620184,
 0.5945586817373838,
 0.5680539480267797,
 0.99849562057684,
 0.8966767491907432,
 1.0785352733927858,
 0.882429373909196,
 1.6255673482687707,
 1.332305083312579,
 0.3998926331277901,
 0.8753950062214008,
 1.1093699299065083,
 0.9453989497489721,
 0.426009411836067,
 1.1165635206479139,
 0.6441653442148076,
 1.554831337481562,
 1.2246906947682488,
 1.0475534089576761,
 1.2659652307140092,
 1.3163473335879616,
 1.7102859365613992,
 1.0279073155281848,
 0.5062278731367522,
 1.5216998448641537,
 0.7323986759314394,
 1.0194973367377909,
 0.9510191000938281,
 0.8263464399974317,
 0.491788194717675,
 1.6042322629709798,
 1.1813886470295218,
 0.17720406360187924,


In [5]:
%timeit [x + y for (x, y) in zip(list_1, list_2)]

10 loops, best of 3: 75.1 ms per loop


In [7]:
import numpy as np

arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

In [9]:
type(arr_1), type(arr_1)

(numpy.ndarray, numpy.ndarray)

In [10]:
arr_1.shape

(1000000,)

In [11]:
arr_1.dtype

dtype('float64')

In [12]:
sum_arr = arr_1 + arr_2
sum_arr[:3]

array([ 0.99287433,  1.0845018 ,  0.56634018])

In [13]:
%timeit arr_1 + arr_2

100 loops, best of 3: 1.77 ms per loop


## 배열 생성과 로딩

### 배열 생성

In [15]:
import numpy as np

print("ones", np.ones(5))
print("arange", np.arange(5))
print("linspace", np.linspace(0., 1., 5))
print("random", np.random.uniform(size=3))
print("custom", np.array([2, 3, 5]))

ones [ 1.  1.  1.  1.  1.]
arange [0 1 2 3 4]
linspace [ 0.    0.25  0.5   0.75  1.  ]
random [ 0.50310384  0.03817774  0.79469524]
custom [2 3 5]


In [16]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [17]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1])

In [19]:
np.arange(5).astype(np.float64)

array([ 0.,  1.,  2.,  3.,  4.])

## 기본 배열 조작

In [20]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
x_row = x.reshape((1, -1))
x_row

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [23]:
x_col = x.reshape((-1, 1))
x_col

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [29]:
x_col = x[:, np.newaxis]
x_col

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [26]:
np.dot(x_col, x_row)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [27]:
x_row * x_row

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [28]:
x_row * x_col

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [29]:
x_col * x_row

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [31]:
x_row + x_col

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [32]:
x_col + x_row

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [30]:
np.random.normal?

In [19]:
np.random.normal()

-1.3830817562945124

In [14]:
np.random.normal(size=10)

array([ 0.0692236 , -1.11073195, -0.88955361, -0.88206675, -0.54720631,
        1.67110477,  1.62475274, -0.50952793, -2.67209036, -0.97709091])

In [15]:
np.random.normal(1.0, 2.0, 10)

array([-0.19153935,  1.6333086 ,  2.40243397,  2.51169666,  1.22997518,
        0.66147795,  3.29048915, -1.82214951,  2.0668419 ,  2.58241805])

In [33]:
mu, sigma = 0, 0.1
s = np.random.normal(mu, sigma, 10)
s

array([-0.15792247, -0.00962535,  0.05098456,  0.04886004,  0.15815934,
       -0.08365946, -0.09407199,  0.02367047, -0.08384217,  0.03712867])